export const BUSINESS_CATEGORIES = [
  'E-commerce',
  'Consulting',
  'Freelancing',
  'Retail',
  'Telecommunication',
  'Manufacturing',
  'Food & Beverage',
  'Education',
  'Real Estate',
  'Technology',
  'Healthcare',
  'Finance',
  'Agriculture',
  'Transportation',
  'Entertainment',
  'Agency',
  'Hospitality',
  'Legal Services',
  'Logistics',
  'Marketing',
  'Nonprofit',
];
